spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/petshop
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
#  packages-to-scan:
#    - com.pet.controller

