import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "@/app/providers";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
      >
        <TRPCProvider>
         <div className="font-sans flex flex-col min-h-screen w-full">
               {/* Header */}
               <header className="w-full sticky top-0 z-50 shadow-lg">
                 <Header />
               </header>
         
               {/* Main content */}
               <main className="flex-1 bg-[#F5D7B7] w-full">
                 {children}
               </main>
         
               {/* Footer */}
               <footer className="w-full">
                 <Footer />
               </footer>
             </div>
        </TRPCProvider>
      </body>
    </html>
  );
}
